// client/src/components/deleteRoom.tsx
import React, { useState } from "react";
import { deleteRequest, Room } from "../requests/requests";
import { ErrorAlert } from "./error";

interface DeleteProps {
  room: Room,
  onDelete: Function,
  onCancel: Function
}

export const DeleteRoomModal: React.FC<DeleteProps> = ({room, onDelete, onCancel}) => {
  const [err, setErr] = useState('')
  const [show, setShow] = useState(false);
  
  const handleDeleteSubmit = () => {
    deleteRequest(`rooms?room=${room.codigo}`)
    .then(_ => onDelete())
    .catch(err => {
      setErr(err.message);
      setShow(true);
    })
  }

  return (
    <>
      <div className="col-span-12 p-5 text-center">
        <p className="text-xl">Esta seguro de que desea eliminar la habitacion {room.codigo}?</p>
      </div>
      <div className="col-span-12 p-5">
        <div className="flex justify-between">
          <div className="w-full flex justify-center">
            <button onClick={_ => onCancel()}  className="w-[45%] text-contrast bg-secondary hover:bg-secondary text-last font-bold py-2 px-4 rounded">
              Cancelar
            </button>
          </div>
          <div className="w-full flex justify-center">
            <button onClick={handleDeleteSubmit}  className="w-[45%] text-contrast bg-red text-last font-bold py-2 px-4 rounded">
              Confirmar
            </button>
          </div>
        </div>
      </div>
      <div className="col-span-12 p-5">
        <ErrorAlert message={err} show={show} />
      </div>
    </>
  )
}

// client/src/components/rooms/DeleteRoom.svelte
<script lang="ts">
  import { deleteRequest } from "../../request";
  import type { ModalEvents, Room } from "../../types";
  import { createEventDispatcher } from "svelte";
  import Button from "../Button.svelte";
  import ErrorAlert from "../ErrorAlert.svelte";

  const dispatch = createEventDispatcher<ModalEvents<Room>>();

  export let room: Room;
  let error = "";
  let showError = false;

  const handleDelete = () => {
    showError = false;
    deleteRequest<any>(`rooms/${room.code}`)
      .then(() => dispatch("delete", room))
      .catch(err => {
        error = err.message;
        showError = true;
      });
  };
</script>

<div class="col-span-12 mb-4">
  <div class="text-xl font-bold text-center">
    <span class="text-slate-900">Esta seguro de eliminar la habitacion {room.code} ?</span>
  </div>
</div>
<div class="col-span-12">
  <div class="flex flex-col gap-5 items-center justify-around w-full p-2">
    <div class="w-1/5">
      <button type="button" on:click={handleDelete} class="bg-red-700 hover:bg-red-600 text-slate-100 transition-all rounded-md p-2 font-bold w-full active:transform active:translate-y-1">
        Eliminar
      </button>
    </div>
    <div class="w-1/5">
      <Button text="Cancelar" click={() => dispatch("close")} />
    </div>
  </div>
</div>
<div class="col-span-12">
  <ErrorAlert message={error} show={showError} />
</div>
