// client/src/components/Table.svelte
<script lang="ts">
  export let columns: string[];
</script>

<div class=" bg-slate-100 p-3 min-h-full w-full">
  <div class="overflow-auto lg:overflow-visible">
    <table class="table text-slate-900 border-separate space-y-6 text-md w-full">
      <thead class="bg-white text-slate-900">
        <tr>
          {#each columns as column}
            <th class="text-center p-2">{column}</th>
          {/each}
        </tr>
      </thead>
      <tbody>
        <slot />
      </tbody>
    </table>
  </div>
</div>
<style>
  :global(.table) {
    border-spacing: 0 15px;
  }

  :global(.table tr) {
    border-radius: 6px;
    outline: auto;
  }

  :global(tr td:last-child) {
		border-radius: 0 .625rem .625rem 0;
  }

  :global(tr th:first-child) {
    border-radius: .625rem 0 0 .625rem;
  }

  :global(tr td:first-child) {
    border-radius: .625rem 0 0 .625rem;
  }

  :global(tr th:last-child) {
    border-radius: 0 .625rem .625rem 0;
  }
</style>

// client/src/components/table.tsx
import React, { useState } from "react";

interface tableProps {
  columns: Array<string>
  rows: JSX.Element[]
  
}

export const Table: React.FC<tableProps> = (props) => {
  const trStyle = {borderRadius: "20px"}
  return (
    <div className="w-full p-4">
      <div className="overflow-auto lg:overflow_visible w-full">
        <table className="table text-gray-400 border-separate border-spacing-y-2 space-y-6 text-md w-full">
          <thead className="bg-contrast text-secondary rounded rounded-md">
            <tr  className="" style={trStyle}>
              {props.columns.map(col => (<th key={col} className="p-3 text-center">{col}</th>))}
            </tr>
          </thead>
          <tbody>
            {props.rows}
          </tbody>
        </table>
      </div>
    </div>
  )
}
